In [1]:
import pandas as pd
import numpy as np

In [ ]:
orders = pd.read_csv("data/orders.csv")
order_products = pd.read_csv("data/order_products__prior.csv")
products = pd.read_csv("data/products.csv")

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\yashk\AppData\Local\Temp\ipykernel_4740\1017154782.py:1: SyntaxWarning: invalid escape sequence '\M'
  orders = pd.read_csv("D:\ML\ML Projects\MLDiaries06_MarketBasketAnalysis\data\orders.csv")

In [3]:
orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [4]:
orders.columns

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='object')

In [5]:
order_products.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [6]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [7]:
order_items = (
    order_products
    .merge(products, on="product_id", how="left")
    .merge(orders[["order_id", "user_id", "order_number"]], 
           on="order_id", how="left")
)

In [8]:
order_items.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
product_name         0
aisle_id             0
department_id        0
user_id              0
order_number         0
dtype: int64

In [9]:
order_items.head()

,order_id,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,user_id,order_number
0,2,33120,1,1,Organic Egg Whites,86,16,202279,3
1,2,28985,2,1,Michigan Organic Kale,83,4,202279,3
2,2,9327,3,0,Garlic Powder,104,13,202279,3
3,2,45918,4,1,Coconut Butter,19,13,202279,3
4,2,30035,5,0,Natural Sweetener,17,13,202279,3

In [10]:
orders["order_number"].describe()

count    3.421083e+06
mean     1.715486e+01
std      1.773316e+01
min      1.000000e+00
25%      5.000000e+00
50%      1.100000e+01
75%      2.300000e+01
max      1.000000e+02
Name: order_number, dtype: float64

In [11]:
order_items = order_items.sort_values(
    by=["user_id", "order_number"]
)

In [12]:
order_baskets = (
    order_items
    .groupby(["user_id", "order_number"])["product_name"]
    .apply(list)
    .reset_index()
)

In [13]:
order_baskets.head(10)

   user_id  order_number                                       product_name
0        1             1  [Soda, Organic Unsweetened Vanilla Almond Milk...
1        1             2  [Soda, Pistachios, Original Beef Jerky, Bag of...
2        1             3  [Soda, Original Beef Jerky, Pistachios, Organi...
3        1             4  [Soda, Original Beef Jerky, Pistachios, Organi...
4        1             5  [Soda, Original Beef Jerky, Pistachios, Organi...
5        1             6  [Soda, Original Beef Jerky, Pistachios, Organi...
6        1             7  [Soda, Pistachios, Original Beef Jerky, Organi...
7        1             8  [Original Beef Jerky, Soda, Pistachios, Organi...
8        1             9  [Organic Half & Half, Zero Calorie Cola, Organ...
9        1            10  [Soda, Zero Calorie Cola, Milk Chocolate Almon...

In [14]:
user_sequences = (
    order_baskets
    .groupby("user_id")["product_name"]
    .apply(list)
)

In [15]:
user_sequences = user_sequences[
    user_sequences.apply(len) >= 2
]

In [16]:
sequences = [
    tuple(tuple(items) for items in user_seq)
    for user_seq in user_sequences.tolist()
]

In [17]:
type(sequences), type(sequences[0]), type(sequences[0][0])

(list, tuple, tuple)

In [18]:
MIN_SUPPORT = 200    
MAX_LEN = 3

In [19]:
from prefixspan import PrefixSpan

ps = PrefixSpan(sequences)
ps.maxlen = MAX_LEN

patterns = ps.frequent(MIN_SUPPORT)
len(patterns)

60

In [20]:
patterns[:10]

[(277, [('Coconut Water',)]),
 (1189, [('Soda',)]),
 (484, [('Soda',), ('Soda',)]),
 (269, [('Soda',), ('Soda',), ('Soda',)]),
 (236, [('Organic Yellow Onion',)]),
 (606, [('Clementines',)]),
 (265, [('Popcorn',)]),
 (1390, [('Banana',)]),
 (283, [('Banana',), ('Banana',)]),
 (405, [('Smartwater',)])]

In [21]:
journeys = [
    (support, seq)
    for support, seq in patterns
    if len(seq) >= 2
]

len(journeys)

6

In [22]:
for support, seq in journeys[:5]:
    print(f"Support: {support}")
    print(" → ".join([", ".join(step) for step in seq]))
    print("-" * 50)

Support: 484
Soda → Soda
--------------------------------------------------
Support: 269
Soda → Soda → Soda
--------------------------------------------------
Support: 283
Banana → Banana
--------------------------------------------------
Support: 350
Spring Water → Spring Water
--------------------------------------------------
Support: 202
Spring Water → Spring Water → Spring Water
--------------------------------------------------

In [23]:
def remove_consecutive_duplicates(sequence):
    cleaned = []
    prev = None
    for step in sequence:
        step_set = set(step)
        if step_set != prev:
            cleaned.append(step)
        prev = step_set
    return cleaned

sequences_clean = [
    tuple(remove_consecutive_duplicates(seq))
    for seq in sequences
]

In [24]:
sequences_clean[8]

(('Almond Non-Dairy Yogurt Made From Real Almonds Plain Low Fat',
  'Black Peppercorns',
  'Organic Raspberries',
  'Total 2% with Strawberry Lowfat Greek Strained Yogurt',
  'Total 2% Lowfat Greek Strained Yogurt With Blueberry',
  'Total 0% Peach Yogurt',
  'Total 2% Greek Strained Yogurt with Cherry 5.3 oz',
  'Organic Yellow Peaches',
  'Dairy Free Vanilla Coconut Milk',
  'Organic Bunny Fruit Snacks Berry Patch',
  'Organic Iced Oatmeal Cookie ZBar',
  'Organic Summer Strawberry Bunny Fruit Snacks',
  'Organic AppleApple',
  'Backyard Barbeque Potato Chips',
  'Mini Peanut Butter Sandwich Crackers',
  'Apple Cinnamon GoGo Squeez',
  'Organic Stage 3 Pumpkin Cranberry Apple Baby Food',
  'Butternut Squash Pear Stage 2 Baby Food',
  'Baby Food Stage 2 Blueberry Pear & Purple Carrot',
  'Sunny Days Strawberry Snack Bars',
  'Organic Sunny Days Apple Snack Bars',
  'Cinnamon Crunch Apple Chips',
  'Multigrain Pancake & Waffle Mix',
  'Chicken & Apple Breakfast Sausage',
  'Naturals Savory Turkey Breakfast Sausage',
  'Cherry Vanilla Creme Soda',
  'Natural Vanilla Marshmallows',
  'RapidRise Yeast',
  'Whipped Cream Cheese',
  'Aluminum Foil'),
 ('Organic & Cold-Pressed Vegetable & Fruit Juice Vitality',
  'Organic Yellow Peaches',
  'Organic Raspberries',
  'Fat Free Strawberry Yogurt',
  'Total 2% Lowfat Greek Strained Yogurt With Blueberry',
  'Organic Blackberries',
  'Raspberry Lime Sparkling Seltzer Water',
  'Total 2% Lowfat Greek Strained Yogurt with Peach',
  'Almond Non-Dairy Yogurt Made From Real Almonds Plain Low Fat',
  'Organic Soft Wheat Bread',
  'YoKids Strawberry Banana/Strawberry Yogurt'),
 ('Raspberry Lime Sparkling Seltzer Water',
  'Organic Soft Wheat Bread',
  'Organic & Cold-Pressed Vegetable & Fruit Juice Vitality',
  'Almond Non-Dairy Yogurt Made From Real Almonds Plain Low Fat',
  'YoKids Strawberry Banana/Strawberry Yogurt',
  'Fat Free Strawberry Yogurt',
  'Sunny Days Strawberry Snack Bars',
  'Backyard Barbeque Potato Chips',
  'Total 2% with Strawberry Lowfat Greek Strained Yogurt',
  'Total 2% Greek Strained Yogurt with Cherry 5.3 oz',
  'Whipped Cream Cheese',
  'Black Peppercorns',
  'Organic Blackberries',
  'YoKids Squeezers Organic Low-Fat Yogurt, Strawberry',
  'Gluten Free Pretzel Sticks',
  'Spicy Hummus',
  'Classic Original Hommus',
  'Organic American Cheese Singles',
  'Total 0% with Honey Nonfat Greek Strained Yogurt',
  'Cherry Pomegranate Greek Yogurt',
  'Cinnamon Raisin Bread',
  'Organic Frosted Flakes Cereal',
  'Tortilla Chips, Corn, Red Hot Blues',
  'Original Veggie Straws',
  'Ginger Root Beer, Naturally Flavored Zero Calorie Soda, Caffeine Free',
  'Goo Berry Pie Probugs Kefir',
  'Zero Calorie Cola Soda',
  'Honey Nut Cheerios',
  'Organic Smoked Turkey Breast',
  'Caffeine Free Diet Cola All Natural Soda',
  'Dairy Free Vanilla Coconut Milk',
  'White English Muffins',
  'Organic Dried Granny Apple Chips',
  'Krinkle Cut Classic Barbecue Potato Chips',
  'Organic Green Seedless Grapes'))

In [25]:
ps = PrefixSpan(sequences_clean)
ps.maxlen = 3

patterns = ps.frequent(200)

journeys = [
    (support, seq)
    for support, seq in patterns
    if len(seq) >= 2
]

journeys

[(385, [('Soda',), ('Soda',)]),
 (204, [('Banana',), ('Banana',)]),
 (253, [('Spring Water',), ('Spring Water',)]),
 (349, [('Bag of Organic Bananas',), ('Bag of Organic Bananas',)])]

In [26]:
from collections import Counter

item_counts = Counter()
transition_counts = Counter()

for seq in sequences_clean:
    for i in range(len(seq) - 1):
        a = seq[i][0]
        b = seq[i+1][0]
        if a == b:
            transition_counts[a] += 1
        item_counts[a] += 1

confidence = {
    item: transition_counts[item] / item_counts[item]
    for item in transition_counts
}
confidence

{'Soda': 0.2869977791237634,
 'Chipotle Beef & Pork Realstick': 0.21782178217821782,
 'Vanilla Unsweetened Almond Milk': 0.09574468085106383,
 'Antioxidant Infusions Beverage Malawi Mango': 0.21875,
 'Organic Strawberries': 0.13495768340354472,
 'Asparagus': 0.08783505154639175,
 'Original Hummus': 0.14835368109507954,
 'Bag of Organic Bananas': 0.2723365315290333,
 'Whole Milk': 0.26126487498328654,
 'Organic Mung-Bean Sprouts': 0.05429864253393665,
 'Dried Mangos': 0.1568627450980392,
 'Trail Mix': 0.2275132275132275,
 'Organic Baby Spinach': 0.12589084555611751,
 'Natural Lime Flavor Sparkling Mineral Water': 0.2509881422924901,
 'Lime Italian Sparkling Mineral Water': 0.30338983050847457,
 'Chocolate Coconut Milk Beverage': 0.2727272727272727,
 'Unsweetened Premium Iced Tea': 0.17688266199649738,
 'Hard Boiled Eggs': 0.19101123595505617,
 'Clementines': 0.22483279025896072,
 'New Orleans Iced Coffee': 0.2642089093701997,
 'Sparkling Water Grapefruit': 0.2331102613129382,
 'Cold Brew Coffee': 0.2077922077922078,
 'Pure Coconut Water': 0.17019027484143764,
 'Natural Artisan Water': 0.2375495813133539,
 '80% Lean Ground Beef': 0.0707070707070707,
 'Bars Peanut Butter': 0.5263157894736842,
 'Honey Buns': 0.2857142857142857,
 'Oatmeal Crème Pies': 0.18840579710144928,
 'Smartwater': 0.33775633293124246,
 'Tall Kitchen Bag With Febreze Odor Shield': 0.028132992327365727,
 'Dha Omega 3 Vitamin D Milk': 0.26378186129223474,
 'Sparkling Natural Mineral Water': 0.2506187312752377,
 '100% Raw Coconut Water': 0.2472484886064176,
 '1500 Pale Ale': 0.25,
 'Multi Grain Crispbread': 0.06521739130434782,
 'Vanilla Coconut Milk Yogurt': 0.10126582278481013,
 'Pure Sparkling Water': 0.2778498609823911,
 'Vanilla Skyr Nonfat Yogurt': 0.1505226480836237,
 'Michigan Organic Kale': 0.166928011404134,
 'Rainbow Candy': 0.2857142857142857,
 'Banana': 0.2994014899288232,
 'Chubby Hubby Ice Cream': 0.23529411764705882,
 'Krinkle Cut Salt & Fresh Ground Pepper Potato Chips': 0.0851063829787234,
 'Organic Zucchini': 0.0748502994011976,
 'Natural Artesian Bottled Water': 0.3338926174496644,
 'Sea Salt & Vinegar Potato Chips': 0.09769484083424808,
 'Organic Hass Avocado': 0.1577395361119669,
 'Hass Avocados': 0.2322214500810748,
 'Electrolyte Enhanced Water': 0.28512609366958314,
 'Organic Bagged Carrots': 0.04555808656036447,
 'Semi-Sweet Mini Chocolate Chips': 0.034482758620689655,
 'Classic Air-Puffed Vanilla Flavored Marshmallows': 0.04560260586319218,
 'Imported Mineral Water': 0.28362573099415206,
 'Organic Strawberry Chia Lowfat 2% Cottage Cheese': 0.2,
 'Whipped Cream Cheese': 0.07072599531615925,
 'Unsweetened Almondmilk': 0.18451400329489293,
 'Gluten Free Sliced Mountain White Bread': 0.12549019607843137,
 'Organic Whole String Cheese': 0.13849821215733016,
 'Peach Pear Flavored Sparkling Water': 0.14141922496225465,
 'Great White Bread': 0.15384615384615385,
 'Gluten Free & Dairy Free Thai Red Curry With Organic Jasmin Rice & Vegetables': 0.12280701754385964,
 'Apple Honeycrisp Organic': 0.155956678700361,
 'Organic Cucumber': 0.10793319415448852,
 'Dried Mango': 0.245836109260493,
 'Bunched Cilantro': 0.061732725359522976,
 'Lactose Free Blueberry Yogurt': 0.24166666666666667,
 'Authentic French Brioche': 0.24124513618677043,
 'Petit Suisse Fruit': 0.24615384615384617,
 'Organic Reduced Fat Milk': 0.3111716621253406,
 'English Seedless Cucumber': 0.07651006711409396,
 'smartwater® Electrolyte Enhanced Water': 0.1970217640320733,
 'Multi Grain Sandwich Thins': 0.07643312101910828,
 'Granny Smith Apples': 0.1568253968253968,
 'Low Fat 1% Milk': 0.24425887265135698,
 'Liquid Egg Whites': 0.21410992616899097,
 'Apples': 0.22917513206013815,
 'Organic Italian Parsley Bunch': 0.04294478527607362,
 'Milk, Organic, Vitamin D': 0.2866002631084383,
 'Adult Grain-Free & Poultry-Free Dog Food': 0.09523809523809523,
 'Organic Unsweetened Almond Milk': 0.16808424463345484,
 'Crunch Chocolate Peanut Butter Granola Bar': 0.25,
 'Organic Creamy Peanut Butter': 0.03602811950790861,
 'Organic Pink Lemonade Bunny Fruit Snacks': 0.17857142857142858,
 'Organic Graham Crunch Cereal': 0.02054794520547945,
 'Unsweetened Original Almond Breeze Almond Milk': 0.16423132331755505,
 'Organic Heritage Flakes Cereal': 0.12949640287769784,
 'Gluten Free Honey Almond Granola': 0.2,
 'Oatmeal Square Banana Dark Chocolate': 0.16666666666666666,
 'Annie Peely Fruit 4.5 Z': 0.05,
 'Sea Salt Soiree Intense Dark Chocolate Squares': 0.16666666666666666,
 'Raspberries': 0.22995594713656387,
 'Vegetarian Roast': 0.08,
 'Organic Cinnamon Crunch Cereal': 0.052060737527114966,
 'Organic Lemonade': 0.16177957532861476,
 'Vanilla Animal Cookies': 0.07692307692307693,
 'Cheez-It Cheddar Cracker': 0.17091454272863568,
 'Organic 2% Reduced Fat Milk': 0.21365583270345176,
 'Protein Zone Protein Juice Smoothie': 0.17272727272727273,
 'Organic Ginger Root': 0.044005270092226614,
 'Organic Granny Smith Apple': 0.1420055354481584,
 'Gluten-Free Multi Seed Rice Bread': 0.07142857142857142,
 'Mini Baguette': 0.08333333333333333,
 'Original Bomb Pops Ice Pops': 0.15384615384615385,
 'Coke': 0.19654427645788336,
 'Organic Gala Apples': 0.1521968365553603,
 'Whipped Mixed Berry Tub': 0.5263157894736842,
 'Lemon-Lime 12 Pack Soda': 0.19615384615384615,
 'Organic Fuji Apple': 0.17127277233857974,
 'Boneless Skinless Chicken Breasts': 0.11971699869670452,
 'Lemon Hummus': 0.1330309901738473,
 'Organic  Whole Milk': 0.30761316872427985,
 'Organic Whole Milk': 0.2701181570299937,
 '2% Reduced Fat Organic Milk': 0.23118622448979592,
 'Sweet & Salty Nut Almond Granola Bars': 0.18045112781954886,
 'Pineapple Chunks': 0.1064410480349345,
 'Roasted Pine Nut Hummus': 0.15769712140175218,
 'Half And Half Cream': 0.20999275887038377,
 'Prosciutto Di Parma': 0.1276595744680851,
 'Enlightened Organic Raw Kombucha': 0.2965779467680608,
 'Red Raspberries': 0.16103896103896104,
 'Special Reserve Extra Sharp Cheddar Cheese': 0.09147609147609148,
 'Activia Vanilla Low Fat Yogurt': 0.19393939393939394,
 'Lactose Free Fat Free Milk': 0.2696747114375656,
 'Chocolate Lowfat Milk': 0.12636165577342048,
 'Large Grade AA Eggs': 0.10478654592496765,
 'Pure Almond Unsweetened Original Almond Milk': 0.20417633410672853,
 'Blueberries Pint': 0.07308970099667775,
 'Plain Non-Fat Greek Yogurt': 0.12035398230088495,
 'Organic Lightly Salted Butter': 0.11538461538461539,
 'Sleepytime Extra Herbal Tea Bags': 0.03125,
 'Eggo Buttermilk Waffles': 0.07734806629834254,
 'Yobaby Organic Plain Yogurt': 0.16146993318485522,
 'Crispy Cheddar Crackers': 0.09032258064516129,
 'Grated Parmesan Cheese': 0.015706806282722512,
 'Lactose Free 2% Reduced Fat Milk': 0.25339366515837103,
 'Grassfed Whole Milk Plain Yogurt': 0.1471861471861472,
 'Organic Spring Mix Salad': 0.09562289562289562,
 'Organic Kiwi': 0.14073615836684195,
 'French Roast, Dark Roast K-Cups': 0.14906832298136646,
 'Lemon Seltzer Water': 0.24545454545454545,
 'Chicken & Vegetable Dumplings Potstickers': 0.09259259259259259,
 'Frontier Straight 95% Rye Mash Whiskey': 0.04878048780487805,
 'Sparkling Water': 0.30451127819548873,
 'G2 Low Calorie Lemon Lime Sports Drink': 0.23076923076923078,
 'Organic 7 Grain with Flax Bread': 0.1987179487179487,
 'Whole Organic Omega 3 Milk': 0.32527264106211473,
 'Organic Reduced Fat Omega-3 Milk': 0.25705939629990265,
 '2% Reduced Fat Milk': 0.2511342016683741,
 'OTC Acid Reducer': 0.03333333333333333,
 'Cheese Stuffed Crust Pepperoni Pizza': 0.07142857142857142,
 'Organic Chicken Noodle Soup': 0.06517311608961303,
 'Authentic French Brioche Hamburger Buns': 0.06778087279480037,
 'White Chocolate Macadamia Nut Energy Bar': 0.16938110749185667,
 'Organic Roasted Turkey Breast': 0.10874938210578348,
 'Reduced Fat Chocolate Milk': 0.19653179190751446,
 'Organic Coconut Milk': 0.0381201044386423,
 'Organic Mango Chunks': 0.09323583180987204,
 'Lemon Ginger Sparkling Probiotic Drink': 0.2972536348949919,
 'Spinach And Ricotta Ravioli': 0.1375,
 'Original Party Mix Catt Treats': 0.42105263157894735,
 'Pinot Grigio': 0.36,
 'Classic Wheat Bread': 0.1,
 'Lime Sparkling Water': 0.19385995170748535,
 'Teriyaki Chicken': 0.08571428571428572,
 'Earl Grey Tea': 0.033707865168539325,
 'Extra Fancy Unsalted Mixed Nuts': 0.2650968477022408,
 'Green Seedless Grapes': 0.166545981173063,
 'Red Seedless Grapes': 0.11444141689373297,
 'Seedless Red Grapes': 0.1321001800622033,
 'Organic Blackberries': 0.12556266287609572,
 'Cold Brew Coffee Double Espresso with Almond Milk': 0.18181818181818182,
 'Almond Milk Peach Yogurt': 0.1518624641833811,
 'Dairy-Free Chive Cream Cheese': 0.18093385214007782,
 'Brazilian Cheese Bread Original Cheddar and Parmesan': 0.10952380952380952,
 'Organic Extra Firm Tofu': 0.07822308063737325,
 'Kelp Noodles': 0.0625,
 'Sierra Trail Mix Energy Bar': 0.06451612903225806,
 "Fakin' Bacon Organic Smoky Tempeh Strips": 0.08695652173913043,
 'Lemon Verbena Laundry Detergent': 0.03225806451612903,
 'Total 0% Greek Yogurt': 0.17575757575757575,
 'Fresh Cauliflower': 0.06037344398340249,
 'Half & Half': 0.16432933725401494,
 'Butter': 0.04659498207885305,
 'Unsweetened Watermelon Water': 0.18038528896672504,
 'Organic Plain Whole Milk Yogurt': 0.14807692307692308,
 'Dairy Free Unsweetened Vanilla Coconut Milk': 0.19298245614035087,
 'Unsweetened Coconut Milk Beverage': 0.13455328310010764,
 'Almond Breeze Original Almond Milk': 0.18538565629228687,
 'Cola': 0.22154850746268656,
 'Honeycrisp Apple': 0.15316104540808878,
 'Fresh Squeezed Grapefruit Juice': 0.2,
 'Cold-Pressed Organic Grapefruit': 0.2867132867132867,
 'Guacamole': 0.14945181765724178,
 'Non Fat Acai & Mixed Berries Yogurt': 0.17509727626459143,
 'Reduced Fat Milk 100% Lactose Free': 0.2146341463414634,
 'Organic Light Brown Sugar': 0.017543859649122806,
 'Crunchy Peanut Butter Energy Bar': 0.09737827715355805,
 'Russet Potato': 0.05939226519337017,
 'Natural Spring Water': 0.3039236939085194,
 'Distilled Water': 0.23915989159891599,
 'Oven Roasted Turkey Breast': 0.10979462875197472,
 '100% Whole Wheat English Muffin 6 Ct': 0.18085106382978725,
 'Specials Sourdough Pretzels': 0.2727272727272727,
 'Spring Water': 0.3509870660313138,
 'Royal Gala Apples': 0.11961722488038277,
 'Organic Baby Spinach Salad': 0.1779816513761468,
 'Sparkling Mineral Water': 0.3268534400609872,
 'Kale Greens Bunch': 0.125,
 'Organic Small Bunch Celery': 0.06670074111934578,
 'Organic Avocado': 0.18372969837587008,
 'Organic Hot House Tomato': 0.054285714285714284,
 'Organic Chicken Strips': 0.10249307479224377,
 'Kids Organic Chocolate Chip ZBars': 0.1245136186770428,
 'Deli Fresh Smoked Turkey Breast': 0.12457912457912458,
 'DanActive Vanilla Probiotic Dairy Drink': 0.2558139534883721,
 'Total 2% Lowfat Greek Strained Yogurt with Peach': 0.18783269961977186,
 'Organic Chicken Stock': 0.0780399274047187,
 'Alaskan Salmon Burgers': 0.16927083333333334,
 'Special Recipe White Bread': 0.05,
 'Creamy Almond Butter': 0.07761578044596913,
 'Organic Lowfat 1% Milk': 0.3069926094371802,
 'Organic Blueberries': 0.11371659102370146,
 'Shredded Mexican Blend Cheese': 0.09523809523809523,
 'Strawberries': 0.15628546631951398,
 'Cucumber Kirby': 0.1265020467450152,
 'European Cucumber': 0.09582309582309582,
 'Butterhead Lettuce': 0.17248459958932238,
 'Rocky Mountain Sourdough Bread': 0.18604651162790697,
 'Fat Free Milk': 0.2451796224883296,
 'Variety Snack Pack': 0.05357142857142857,
 'Organic Fat Free Milk': 0.2895193977996526,
 'Organic Vanilla Almond Milk': 0.23915461624026696,
 '1% Low Fat Milk': 0.2872032426172554,
 'Pure Baking Soda': 0.0196078431372549,
 'Spearmint Sugar-Free Gum': 0.049019607843137254,
 'Organic Unsweetened Vanilla Almond Milk': 0.24237623762376237,
 'Gluten Free Organic Oat Based Cereal': 0.2608695652173913,
 'Cold-pressed, Deliciously Hydrating Watermelon Water': 0.2800608828006088,
 'Cafe Latte Pure Lightly Sweetened Iced Coffee With Almond Milk': 0.18156424581005587,
 'Organic Small Curd Cottage Cheese': 0.134375,
 'Smok Cured Turkey Bacon': 0.1630170316301703,
 'BoomChocoBoom Dark Chocolate Bar': 0.19047619047619047,
 'Diet Cherry Coke': 0.1588785046728972,
 'Creamy Caramel Filled Hard Candies': 0.25,
 'Whole Jersey Milk Low Pasteurized': 0.30648330058939094,
 'Chocolate Protein Soy & Dairy Protein Shake': 0.34759358288770054,
 'Chunky Guacamole': 0.16666666666666666,
 'Sunflower Seeds': 0.09090909090909091,
 'Coconut Chocolate Chip': 0.09523809523809523,
 'French Vanilla Coffee Creamer': 0.1440162271805274,
 'Light Vanilla Soymilk': 0.18859649122807018,
 'Celery Sticks': 0.10458715596330276,
 'Uncured Genoa Salami': 0.1051040967092008,
 'Organic Yellow Onion': 0.06620209059233449,
 'Organic Tomato Cluster': 0.0758150113722517,
 'Organic Sunday Bacon': 0.061936936936936936,
 'Organic Grade A Free Range Large Brown Eggs': 0.12991527264827288,
 'Ice Cream Bars': 0.18487394957983194,
 'Organic Mint': 0.0684931506849315,
 'Sustainably Soft Bath Tissue': 0.038811400848999394,
 'Unsweetened Vanilla Almond Milk': 0.16871752802843862,
 'Organic Reduced Fat 2% Milk': 0.24428782539502103,
 'Large Alfresco Eggs': 0.18352558414670217,
 'Concentrated Cold Brew Coffee': 0.16170212765957448,
 'Grade A Large White Eggs': 0.11299435028248588,
 'Vanilla Almond Breeze Almond Milk': 0.2046521553563807,
 'Cheddar Snack Mix': 0.08333333333333333,
 'Air Chilled Breaded Chicken Breast Nuggets': 0.1187800963081862,
 'Root Beer': 0.11269614835948645,
 'Organic Red Bell Pepper': 0.09034267912772585,
 'Cage Free Brown Eggs-Large, Grade A': 0.10415200562983815,
 '100% Liquid Egg Whites': 0.17791411042944785,
 'Evaporated Milk': 0.08450704225352113,
 'Sugar Free Italian Sweet Creme Coffee Creamer': 0.14383561643835616,
 'Alpine Spring Water': 0.28211920529801326,
 'Cannellini White Kidney Beans No Salt Added': 0.02564102564102564,
 'Ginger Beer Premium': 0.18888888888888888,
 'Good Seed Organic Thin Sliced Bread': 0.08842105263157894,
 'Baby Cucumbers': 0.27220543806646524,
 'Almond Breeze Chocolate Almond Milk': 0.1099476439790576,
 'Thin Crust Margherita Pizza with Fresh Mozzarella & Basil': 0.11284046692607004,
 'Zero Calorie Cola': 0.2651162790697674,
 'Classic Mix Variety': 0.07252747252747253,
 'Ezekiel 4:9 Bread Organic Sprouted Whole Grain': 0.09564233163554046,
 'Home Style Beefless Tips': 0.13333333333333333,
 'Grain Free Turkey & Salmon Formula Cat Food': 0.1865671641791045,
 'Jalapeno Hummus': 0.1751227495908347,
 'Coconut Water': 0.21067259588660367,
 'Organic Large Grade AA Omega-3 Eggs': 0.14272644098810613,
 'Gluten Free Plain Bagels': 0.068,
 'Small Curd Lowfat 2% Milkfat Cottage Cheese': 0.19152854511970535,
 'Heavy Whip Cream': 0.2233502538071066,
 'Grassmilk 2% Reduced Fat Milk': 0.24392614188532555,
 'Vitamin D Organic Milk': 0.26424870466321243,
 'Organic Large Extra Fancy Fuji Apple': 0.16343534689953534,
 'Premium Unsweetened Iced Tea': 0.21679064824654623,
 'Tomato Yellow Cherry': 0.11,
 '100% Lactose Free Fat Free Milk': 0.22583139984532097,
 'Multi Grain Waffles': 0.09157509157509157,
 'Pasture Raised Eggs': 0.1746031746031746,
 'Original Pure Creamy Almond Milk': 0.17761989342806395,
 'Carmel Peanut Perfectio': 0.25,
 'Grow & Gain Strawberry Nutrition Shake,': 0.125,
 'Farmhouse Mac & Cheese': 0.05263157894736842,
 'Organic Basmati Rice': 0.15789473684210525,
 'Organic Large Grade A Brown Eggs': 0.15121668597914253,
 'Stage 2 Sweet Potato Corn & Apple Baby Food': 0.14705882352941177,
 'Little Yums Pumpkin and Banana Teething Wafers': 0.028169014084507043,
 'Peppered Turkey Jerky': 0.23018867924528302,
 'Roasted Seaweed Snacks': 0.13725490196078433,
 'The Peruvian Burrito': 0.09302325581395349,
 'Bean & Cheese Burrito': 0.19184652278177458,
 'Organic Half & Half': 0.19216530348687041,
 'Frozen Organic Wild Blueberries': 0.07964601769911504,
 'Mini Seedless Cucumbers': 0.13056379821958458,
 '24 Hr Acid Reducer': 0.2,
 'Beef Dinner Franks': 0.09482758620689655,
 'French Loaf': 0.19495412844036697,
 'Water': 0.29655906349769423,
 'Tempt Unsweetened Original Hemp Milk': 0.21252796420581654,
 'Organic Medjool Dates': 0.06577181208053691,
 'Lemon Seltzer': 0.3017241379310345,
 'Healthy Grains Oats & Honey Clusters with Toasted Coconut Gluten Free': 0.08974358974358974,
 'Mountain Spring Water': 0.25448028673835127,
 'Burrata Mozzarela Cheese': 0.11666666666666667,
 'Crackers Harvest Whole Wheat': 0.10071942446043165,
 'Raisin Crunch Sprouted Granola': 0.3888888888888889,
 'Naturals Chicken Nuggets': 0.0547112462006079,
 'Red Vine Tomato': 0.10864128924701306,
 'YoKids Squeezers Organic Low-Fat Yogurt, Strawberry': 0.10903659447348768,
 'Gluten Free Uncured Frozen Pepperoni Pizza': 0.18702290076335878,
 '100% Natural No Salt Added Tomato Sauce': 0.05555555555555555,
 'Arancita Rossa': 0.1414141414141414,
 'Original Popcorn': 0.13232104121475055,
 '100% Natural Spring Water': 0.2734319943622269,
 'Diet Orange Soda': 0.3147208121827411,
 'Deli Fresh Honey Shaved Smoked Ham': 0.06382978723404255,
 'Milk Chocolate Candies, Bonus Bag': 0.030303030303030304,
 'Diet Ginger Ale': 0.1941747572815534,
 'Iceberg Lettuce': 0.10983397190293742,
 'Garlic Hummus': 0.12910284463894967,
 'Mozzarella Style Slices': 0.16666666666666666,
 'Organic Eggs Large': 0.16129032258064516,
 'Hand Dipped Basket Whole Milk Ricotta': 0.06521739130434782,
 'Sharp Cheddar Cheese': 0.07186629526462396,
 'Sweet Potato Tortilla Chips': 0.10698689956331878,
 'Non Fat Greek Yogurt': 0.2536873156342183,
 'Orange Juice': 0.21004016064257028,
 'Trop50 No Pulp Orange Juice w/ Calcium + Vitamin D, 50% Less Sugar & Calories': 0.11643835616438356,
 'Honey Wheat Enriched Bread': 0.15699658703071673,
 'Eggo Pancakes Minis': 0.10852713178294573,
 'Herb Crackers': 0.037383177570093455,
 'Organic Large White Flesh Peach': 0.09053497942386832,
 'Mango Chunks': 0.07802690582959641,
 'Organic Baby Kale': 0.09866666666666667,
 "Crunchy Oats 'n Honey Granola Bars": 0.09618008185538882,
 'Non-Scratch Scrub Sponges': 0.023952095808383235,
 'Tzatziki': 0.10979228486646884,
 'Organic Raspberries': 0.1716306775874907,
 'Broccoli Rabe': 0.09012875536480687,
 'Gluten Free Whole Grain Bread': 0.15058179329226556,
 'Original Enriched Rice Drink': 0.1276595744680851,
 'Strawberry Preserves': 0.04197271773347324,
 'Organic AppleApple': 0.12064676616915423,
 'Vegan Oatmeal Chocolate Chip Cookies': 0.1282051282051282,
 'Organic Plain Kefir': 0.13518197573656845,
 'Organic Just Tart Cherry Juice': 0.13333333333333333,
 'Farmhouse Culture Classic Caraway Kraut': 0.013333333333333334,
 'Natural Classic Pork Breakfast Sausage': 0.06438631790744467,
 'Natural Clean': 0.2,
 'Santa Fe Fiesta Salad': 0.22433460076045628,
 'Organic Raw Kombucha Gingerade': 0.2659537771645395,
 'Pull Ups Girls Learning Designs Training Pants': 0.13793103448275862,
 'Grassmilk Organic Fat Free Milk': 0.23076923076923078,
 'Mini Babybel Light Semisoft Edam Cheeses': 0.10973084886128365,
 'Tomatoes, Crushed, Organic': 0.03076923076923077,
 'Flax Plus Organic Pumpkin Flax Granola': 0.11302211302211303,
 'Vanilla Protein Protein Shake': 0.3416370106761566,
 'Dairy Free Gluten Free Cookie Dough Coconut Milk Frozen Dessert': 0.08433734939759036,
 'Ginger Root Beer, Naturally Flavored Zero Calorie Soda, Caffeine Free': 0.17781690140845072,
 'Gluten Free Mini Pretzels': 0.1,
 'Mini Classic Ice Cream': 0.17073170731707318,
 'Vanilla Almond Breeze': 0.18433931484502447,
 'Anejo Tequila': 0.6730769230769231,
 'Dry Roasted Almonds': 0.17889087656529518,
 'Lacinato Kale Og': 0.081145584725537,
 'Milk, Vitamin D': 0.1420814479638009,
 'Lager': 0.14942528735632185,
 'Extra Beer Bottles': 0.07392996108949416,
 'Frozen Organic Blueberries': 0.19047619047619047,
 'Pure Water': 0.23550087873462214,
 'Sweet Onion': 0.026657552973342446,
 'Freshly made pasta layered between a rich meat sauce and topped with Real Mozzarella cheese Lasagna with Meat & Sauce': 0.14285714285714285,
 'Veggie Chips': 0.1462925851703407,
 'Double Fiber Bread': 0.11801242236024845,

In [30]:
def recommend_reorder(last_purchased_item, habit_confidence, min_confidence=0.25):
    """
    Habit-based reorder recommender using confidence only
    """
    if last_purchased_item not in habit_confidence:
        return f"No habit data available for '{last_purchased_item}'."
    
    confidence = habit_confidence[last_purchased_item]
    
    if confidence >= min_confidence:
        return (
            f" Recommend reordering: {last_purchased_item} "
            f"(habit confidence = {confidence:.2f})"
        )
    else:
        return f"Weak reorder habit for '{last_purchased_item}' (confidence = {confidence:.2f})"

In [31]:
print(recommend_reorder("Soda", confidence))
print(recommend_reorder("Bag of Organic Bananas", confidence))
print(recommend_reorder("Asparagus", confidence))
print(recommend_reorder("Milk", confidence))

 Recommend reordering: Soda (habit confidence = 0.29)
 Recommend reordering: Bag of Organic Bananas (habit confidence = 0.27)
Weak reorder habit for 'Asparagus' (confidence = 0.09)
Weak reorder habit for 'Milk' (confidence = 0.24)